// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBH-p3Jb0YRmh3Qcr3YQq9zzPRQMJa0I0',
    appId: '1:355980868693:android:8e9cf930720a0377d968dc',
    messagingSenderId: '355980868693',
    projectId: 'inkomoko-smart-task',
    databaseURL: 'https://inkomoko-smart-task-default-rtdb.firebaseio.com',
    storageBucket: 'inkomoko-smart-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAht8mvcO_HcF8B3whAgn-80BGnHlWJBLk',
    appId: '1:355980868693:ios:526f226dc8b48c13d968dc',
    messagingSenderId: '355980868693',
    projectId: 'inkomoko-smart-task',
    databaseURL: 'https://inkomoko-smart-task-default-rtdb.firebaseio.com',
    storageBucket: 'inkomoko-smart-task.firebasestorage.app',
    androidClientId: '355980868693-9532g1apas7pm6h85bm77s8dmvo677kh.apps.googleusercontent.com',
    iosClientId: '355980868693-dc1uiqlknp2hs02mhjokioq4djhg3k0u.apps.googleusercontent.com',
    iosBundleId: 'com.inkomoko.smartTask',
  );
}
